[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/diogoflim/AM/blob/main/3_GD_RegLinSimples/gdlr.ipynb)


# Aprendizado de máquina e decisões dirigidas por dados

**Professor: Diogo Ferreira de Lima Silva (TEP)**

**TPP - UFF**

**Aula 3**

# Gradiente Descendente em Regressão Linear

Nessa aula, vamos implementar o algoritmo gradiente descendente para regressão linear.

Inicialmente, trabalharemos o caso com 1 atributo e depois passaremos para o caso genérico.

In [320]:
### Bibliotecas
import copy
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

## Caso com 1 Atributo

Iniciaremos criando um vetor de valores aleatórios para o nosso alearórios e os respectivos rótulos seguindo um relacionamento linear, conforme realizado na aula 2.

In [567]:
# gerando valores para o nosso atributo x
x = np.array([1.0, 2.0, 3.0, 4.0])   

# gerando valores para os rótulos associados
y = np.array([300.0, 500.0, 780, 1000]) 

In [568]:
print(f"valores de x: \n{x}")
print(f"valores de y: \n{y}")

valores de x: 
[1. 2. 3. 4.]
valores de y: 
[ 300.  500.  780. 1000.]


### Função custo

In [574]:
def custo_total (x, y, w, b):
    m = x.shape[0] 
    custo = 0
    for i in range(m):
        f_wb = w * x[i] + b
        custo = custo + (f_wb - y[i])**2 
    J = (1 / (2 * m)) * custo
    return J

In [575]:
custo_total(x, y, 0, 0)

243550.0

In [585]:
x_novo = np.array( [[1 for i in range (len(x))], 
                    [x[i] for i in range (len(x))]]).T

x_novo

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.]])

In [591]:
w_hat = np.linalg.inv(x_novo.T.dot(x_novo)).dot(x_novo.T).dot(y)

print(f'w = {w_hat[1]} e b = {w_hat[0]}')

print(f'Custo = {custo_total(x,y,w_hat[1], w_hat[0])}')

w = 238.00000000000003 e b = 49.9999999999996
Custo = 134.9999999999996


### Função gradiente

In [592]:
def gradiente(x, y, w, b): 
    m = x.shape[0] # numero de exemplos   
    dj_dw = 0
    dj_db = 0
    # loop nos exemplos 
    for i in range(m):  
        # Primeiro calculamos o valor da função linear no exemplo i
        f_wb = w * x[i] + b 
        # Calculamos a contribuição do exemplo i para as derivadas (no somatório)
        dj_dw_i = (f_wb - y[i]) * x[i] 
        dj_db_i = f_wb - y[i] 
        # Acrescentamos a contribuição de i no valor das derivadas
        dj_db += dj_db_i
        dj_dw += dj_dw_i 
    # Ao deixar o loop, temos o valor dos somatórios associados às derivadas.
    # Ainda precisamos dividir por m
    dj_dw = dj_dw / m 
    dj_db = dj_db / m 
        
    return dj_dw, dj_db

In [595]:
gradiente(x,y, 0, 0)

(-1910.0, -645.0)

### Gradiente Descendente

In [596]:
def gradiente_descente (x, y, w_in, b_in, alfa, num_iters, f_custo, f_gradiente): 
    # Por precaução, vamos guardar o valor de nossos chutes iniciais 
    w = copy.deepcopy(w_in) 
    J_lista = []
    parametros_lista = []
    b = b_in
    w = w_in
    # Em cada iteração i
    for i in range(num_iters):
        # Calculamos o valor das derivadas parciais com a função gradiente
        dj_dw, dj_db = f_gradiente(x, y, w ,b)     
        # Atualizamos o valor dos parâmetros w e b
        b = b - alfa * dj_db                            
        w = w - alfa * dj_dw                            
        # Salvamos o valor de J no iteração i
        J_lista.append(f_custo(x, y, w, b))
        parametros_lista.append([w,b])
    
    return w, b, J_lista, parametros_lista

In [629]:
w, b, J_lista, parametros_lista = gradiente_descente (x, y, w_in = 0, b_in = 0, 
                                                     alfa = 10, num_iters = 10, 
                                                    f_custo = custo_total, f_gradiente = gradiente)

In [637]:
print(f'No ótimo, w = {w_hat[1]}, b = {w_hat[0]}, J = {custo_total(x,y, w_hat[1], w_hat[0])}\n')

print(f'Encontramos w = {w}, b = {b} e J = J = {custo_total(x,y, w, b)}')


No ótimo, w = 238.00000000000003, b = 49.9999999999996, J = 134.9999999999996

Encontramos w = -3.339717580544703e+21, b = -1.1359112448752288e+21 e J = J = 5.195562975598518e+43


In [650]:
for i in range (5):
    print(f'Na iteração = {i+1}, encontramos J = {J_lista[i]}')
print('------------------')
print(f'Custo Final na iteração {len(J_lista)} = {J_lista[-1]}')


Na iteração = 1, encontramos J = 1656428550.0
Na iteração = 2, encontramos J = 11274899040425.0
Na iteração = 3, encontramos J = 7.674545331108854e+16
Na iteração = 4, encontramos J = 5.2238734758329215e+20
Na iteração = 5, encontramos J = 3.5557616658924533e+24
------------------
Custo Final na iteração 10 = 5.195562975598518e+43
