[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/diogoflim/AM/blob/main/4_kNN.ipynb)


# Introdução ao Aprendizado de Máquina

**Professor: Diogo Ferreira de Lima Silva (TEP)**

**Universidade Federal Fluminense**


# Classificação com o Iris dataset

## Entendendo o problema

Nossa base de treinamento contém informações sobre 150 flores, divididas em 3 classes (rótulos):

- 0: "setosa"
- 1: "versicolor"
- 2: "virginica"

Ao todo, temos quatro atributos:

1. largura da sépala em cm
2. comprimento da sépala em cm
3. largura da pétala em cm
4. comprimento da pétala em cm


Com base nos nossos dados, queremos aprender uma forma de classificar novas instâncias.

## Acessando a base de dados

A biblioteca sklearn é muito importante para modelagem de AM. Podemos usá-la para acessar a base de dados iris


In [54]:
from sklearn.datasets import load_iris

In [55]:
(X, y) = load_iris(return_X_y = True)

In [56]:
# Vamos analisar o formato dos nossos dados

print (f' shape da matriz de atributos: {X.shape}')
print (f' shape do vetor de rótulos de atributos: {y.shape}')


 shape da matriz de atributos: (150, 4)
 shape do vetor de rótulos de atributos: (150,)


In [57]:
# Primeiras 10 linhas da matriz de atributos

X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [58]:
# Vetor de rótulos
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Amostragem

Como visto em sala, é importante realizar uma separação entre os dados de treinamento e teste. Isso pode ser feito com a função train_test_split do pacote sklearn

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
# Realizaremos uma separação com 20% dos dados para teste e 80% para treinamento

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size = 0.2)

In [61]:
print (f' shape da matriz de de treinamento: {X_train.shape}')
print (f' shape do vetor de rótulos de treinamento: {y_train.shape}')
print (f' shape da matriz de teste: {X_test.shape}')
print (f' shape do vetor de rótulos de teste: {y_test.shape}')

 shape da matriz de de treinamento: (120, 4)
 shape do vetor de rótulos de treinamento: (120,)
 shape da matriz de teste: (30, 4)
 shape do vetor de rótulos de teste: (30,)


### Normalização

In [62]:
from sklearn.preprocessing import MinMaxScaler

In [63]:
escala = MinMaxScaler()
escala.fit(X_train)

X_train_norm =  escala.transform(X_train)

X_train_norm [:10]

array([[0.58333333, 0.45833333, 0.75862069, 0.70833333],
       [0.30555556, 0.41666667, 0.5862069 , 0.58333333],
       [0.25      , 0.625     , 0.06896552, 0.04166667],
       [0.5       , 0.41666667, 0.65517241, 0.70833333],
       [0.58333333, 0.33333333, 0.77586207, 0.875     ],
       [0.25      , 0.29166667, 0.48275862, 0.54166667],
       [0.38888889, 0.75      , 0.10344828, 0.08333333],
       [0.47222222, 0.29166667, 0.68965517, 0.625     ],
       [0.44444444, 0.41666667, 0.53448276, 0.58333333],
       [0.41666667, 0.25      , 0.5       , 0.45833333]])

## Classificação com o k-NN


In [64]:
# Para aplicar o classificador, podemos importar o método KNeighborsClassifier

from sklearn.neighbors import KNeighborsClassifier

In [65]:
# Inicialmente, criamos o objeto chamando o modelo e passando o hiperparâmetro k=5 (número de vizinhos)

knn = KNeighborsClassifier (n_neighbors= 5)

In [66]:
# Na fase de treinamento, ajustamos a função. Lembrando que, no caso do k-NN, nosso algoritmo é lazy.

# Assim, o treinamento consiste basicamente na memorização dos dados.

knn.fit(X_train_norm, y_train)

KNeighborsClassifier()

In [67]:
# Agora, podemos aplicar nosso método aos exemplos de teste

X_test_norm = escala.transform(X_test)


y_pred = knn.predict(X_test_norm) # y_pred receberá os valores previstos com base nos 5 vizinhos mais próximos

In [68]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

## Performance

Chegou a hora de testarmos a performance que obtivemos em nosso experimento.

Para isso, vamos carregar as métricas inseridas no sklearn e aplicar o método accuracy_score

In [69]:
from sklearn import metrics

In [70]:
metrics.accuracy_score(y_test, y_pred)

1.0

Atingimos uma acurácia de 100% no exemplo.

**Será que obteríamos uma outra acurácia caso a nossa partição (treino / teste) fosse diferente?**

- **Não necessariamente!**

In [71]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X, y, random_state=2, test_size = 0.2)
escala = MinMaxScaler()
X2_train_norm = escala.fit_transform(X2_train)
X2_test_norm = escala.transform(X2_test)
y2_pred = knn.fit(X2_train_norm, y2_train).predict(X2_test_norm)
metrics.accuracy_score(y2_test, y2_pred)


0.9666666666666667

Ou seja, mudando a semente da geração do número aleatório, obtivemos um resultado diferente!

# Aplicando validação cruzada

## r-fold cross validation

1. Particione os dados em r subconjuntos;

2. "Guarde" um subconjunto para o teste da função aprendida pelos demais (r-1) subconjuntos, usados no treinamento;

3.  Calcule a acurácia comparando as previsões com os rótulos verdadeiros do conjunto de teste;

4.  Os passos 2 e 3 são realizados r vezes, cada uma das vezes com um dos subconjuntos usado como teste e os demais no treinamento;  

5. Calcule a média das performances obtidas;

In [72]:
from sklearn.model_selection import cross_val_score

In [73]:
knn = KNeighborsClassifier(n_neighbors= 5)

In [74]:
X_norm = MinMaxScaler().fit_transform(X)

In [75]:
scores = cross_val_score(knn, X_norm, y , cv = 5, scoring= 'accuracy') # cv = 5 partições
scores

array([0.96666667, 0.96666667, 0.96666667, 0.9       , 1.        ])

In [76]:
scores.mean()

np.float64(0.96)

Nossa performance média não foi tão diferente da performance encontrada anteriormente, ficando apenas um pouco abaixo

# Testando diferentes valores de k

In [77]:
X_norm [:10]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ]])

In [78]:
k_range = range(1, 9)
k_scores = []

for k in k_range:
  knn = KNeighborsClassifier(n_neighbors= k)
  scores = cross_val_score(knn, X_norm, y , cv = 5, scoring= 'accuracy')
  k_scores.append(scores.mean())

In [79]:
import pandas as pd

In [80]:
cv_results = pd.DataFrame({'Número de vizinhos': k_range, 'Acurácia': k_scores})
cv_results

Número de vizinhos  Acurácia
0                   1  0.953333
1                   2  0.960000
2                   3  0.953333
3                   4  0.966667
4                   5  0.960000
5                   6  0.966667
6                   7  0.960000
7                   8  0.960000