[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/diogoflim/AM/blob/main/3_GD_RegLinSimples/gdlr.ipynb)


# Introdução ao Aprendizado de Máquina

**Professor: Diogo Ferreira de Lima Silva (TEP)**

**PPGEP - UFF**


Este notebook foi criado é com base em:

- Raschka, S., Liu, Y. H., Mirjalili, V., & Dzhulgakov, D. (2022). Machine Learning with PyTorch and Scikit-Learn: Develop machine learning and deep learning models with Python. Packt Publishing Ltd.

- Veja também o código do capítulo 9: https://github.com/rasbt/machine-learning-book



# Gradiente Descendente em Regressão Linear

Nessa aula, vamos implementar o algoritmo gradiente descendente para regressão linear.

Para isso, utilizaremos os conceitos de Classes em Python.

In [1]:
### Bibliotecas
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

## Implementando o Gradiente Descendente

Inicialmente, vamos criar uma classe vazia, sem nenhum método ou construtor.

In [2]:
class LinearRegressionGD:
    pass

Em python, é comum que iniciemos as classes com um método especial, chamado usando o operador: __init__

Esse será o construtor de nossa classe. Assim, os parâmetros obtigatórios passados na criação de um objeto são aqui definidos. 

Na construção da clase, um parâmetro especial chamado de **self** é sempre criado para se referir ao próprio objeto nas operações posteriores.

In [3]:
class LinearRegressionGD:
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state  
    
    pass

Agora, já poderíamos criar um objeto dessa classe. Os parâmetros definidos foram:

- eta=0.01: a taxa de aprendizado
- n_iter=50: o número de iterações do algoritmo
- random_state=1: a semente aleatória que será utilizada na definição inicial de **w**

Os valores definidos dentro dos parênteses são usados como default caso nenhum parâmetro seja passado na criação do objeto.

In [8]:
lr = LinearRegressionGD()
print(lr.eta)


lr = LinearRegressionGD(eta = .005, n_iter = 20)
print(lr.eta)

0.01
0.005


Ok! Já temos uma classe. Porém, nada ainda pode ser feito. Para isso criaremos os métodos dessa classe. São funções criadas dentro das classes.

Iniciaremos com a função de aprendizado. Seguindo o padrão do sklearn, chamaremos esse método de fit 

In [26]:
class LinearRegressionGD:
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state  
    
    def fit(self, X, y):
        rgen = np.random.RandomState(self.random_state) # cria um gerador de números aleatórios
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=X.shape[1]) # Cria o vetor inicial de pesos
        self.b_ = np.array([0.]) # cria o bias inicial
        self.losses_ = [] # Uma lista vazia para alocarmos as perdas calculadas em cada passo do algoritmo
        
        # Loop no número de iterações
        for i in range(self.n_iter):
            output = np.dot(X, self.w_) + self.b_ # Realiza as previsões dado w e b de momento
            errors = (y - output) # calcula o erro
            self.w_ += self.eta * 2.0 * X.T.dot(errors) / X.shape[0] # Atualiza o w
            self.b_ += self.eta * 2.0 * errors.mean() # Atualiza o b
            loss = (errors**2).mean() # Computa a perda
            self.losses_.append(loss) # Coloca a perda visualizada no passo na lista de perdas
        return self # Retorna o objeto transformado (temos novos w_ e b_)
        
    pass

Agora, já somos capazes de treinar o nosso modelo

In [27]:
# Vamos gerar dados genéricos
def generate_data():
    X = np.random.rand(1000, 5)  
    coef = np.array([2, -1.5, 3, 0.5, -2]) 
    y = X @ coef + np.random.normal(0, 1, 1000)  # Combinação linear e um erro aleatório
    return X, y

X, y = generate_data()


In [28]:
X

array([[0.12930287, 0.26110575, 0.54049439, 0.00214299, 0.88448017],
       [0.79889107, 0.90928485, 0.8504299 , 0.72444671, 0.57141495],
       [0.94032677, 0.34607639, 0.43372853, 0.9091479 , 0.06183561],
       ...,
       [0.53965473, 0.29921897, 0.48521016, 0.09144221, 0.82513254],
       [0.09385249, 0.99851514, 0.60947141, 0.03266667, 0.51408486],
       [0.62105804, 0.5741705 , 0.72741888, 0.7494225 , 0.27915545]])

In [29]:
y

array([-4.12215876e-01,  3.72951407e+00,  1.18283069e+00,  2.15496368e+00,
        1.86716811e+00,  9.12250286e-01,  2.37267049e-01, -2.15816873e-01,
        2.67474842e+00, -1.17126390e-01,  3.66578580e+00, -2.62567227e+00,
        1.09787044e+00, -3.36434656e+00,  2.23341158e+00,  4.22276202e-01,
       -2.05988367e-01, -2.20164011e+00,  2.48622129e+00,  1.12881329e+00,
       -2.43369060e+00,  7.95362061e-01,  3.83980857e+00,  1.45044976e+00,
       -2.93042748e-01, -9.47566260e-01, -1.13466659e-01, -1.35341424e+00,
        8.10789092e-01, -1.03917539e+00,  4.82351747e-01,  3.73152821e-01,
        4.07438641e+00, -2.13488788e-01, -1.59608614e+00, -1.09337750e+00,
        2.76579152e+00, -1.39675299e-01,  1.37762732e+00, -9.06694147e-01,
        2.68763681e+00,  2.29314153e+00,  1.56128863e+00,  4.31732388e+00,
        6.21457886e-01,  8.92506428e-01,  8.26248732e-02, -8.58552299e-01,
        4.13177809e+00,  2.67083737e-01,  2.33044432e+00,  1.29390389e+00,
        1.39659902e+00,  

In [30]:
print(X.shape, y.shape)

(1000, 5) (1000,)


## Dividindo os exemplos em conjuntos de treinamento e teste

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Treinamento do modelo

In [40]:
lr = LinearRegressionGD()
lr.fit(X_train, y_train)

print(lr.w_, lr.b_)


[0.3600064  0.07045389 0.43983381 0.24286611 0.00688516] [0.39948286]


In [41]:
lr.losses_

[3.8407681457113463,
 3.7301497877237084,
 3.629061205461103,
 3.5366376732267533,
 3.4520930964866214,
 3.374712861182274,
 3.303847333326645,
 3.2389059497459995,
 3.1793518462093187,
 3.124696974075123,
 3.07449766103,
 3.028350575533159,
 2.9858890582540245,
 2.946779787128548,
 2.9107197456949665,
 2.877433467128811,
 2.8466705289050775,
 2.8182032752955593,
 2.7918247469820248,
 2.7673467989501317,
 2.744598389541852,
 2.7234240251012602,
 2.7036823460640353,
 2.685244841627796,
 2.667994681310141,
 2.6518256527646296,
 2.636641196191617,
 2.622353526559614,
 2.60888283565169,
 2.596156566677634,
 2.584108754852748,
 2.5726794279442804,
 2.5618140613320306,
 2.5514630826256286,
 2.541581421331798,
 2.5321280994747624,
 2.523065859445518,
 2.5143608256943955,
 2.5059821971891774,
 2.497901967840986,
 2.490094672354534,
 2.4825371551906494,
 2.4752083605392605,
 2.468089141392136,
 2.4611620859784584,
 2.4544113599842534,
 2.447822563120293,
 2.4413825987336293,
 2.4350795552765563

Agora precisamos testar se a os valores se adequam bem aos dados de teste.