[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/diogoflim/AM/blob/main/5_RedesNeurais/RNAs.ipynb)


# Aprendizado de máquina e decisões dirigidas por dados
**Professor: Diogo Ferreira de Lima Silva**

**TPP - UFF**

Exemplos baeados em:
- Geron, Aurélien. Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow. Third Edition, 2021. https://github.com/ageron/handson-ml3

# Perceptron

In [ ]:
# Download libraries
 
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


Vamos aplicar o Perceptron ao conjunto de dados de classificação das flores Iris.

Esse conjunto pode está disponível na bibibioteca sklean através da função load_iris (importada acima)

In [ ]:
dados = load_iris() # load the Iris dataset into a dictionary
dados.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
print(dados.target)

print(f"Os nomes das classes são: {dados.target_names}")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Os nomes das classes são: ['setosa' 'versicolor' 'virginica']


O Perceptron é um algoritmo proposto para classificação binária.

Assim, alteraremos os dados para que o target responda a questão: a flor é da espécie setosa?


In [ ]:
X = dados.data
y = dados.target == 0 # retorna True ou False

In [ ]:
print(f"As 10 primeiras linhas de X são:\n{X[:10]}\n ----------------\n O vetor de targets ficou:\ny = {y}")

As 10 primeiras linhas de X são:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
 ----------------
 O vetor de targets ficou:
y = [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False Fal

In [ ]:
print(f"O shape da matriz X é: {X.shape}\nO vetor y tem {len(y)} valores")


O shape da matriz X é: (150, 4)
O vetor y tem 150 valores


Vamos separar o conjunto de dados entre treinamento e teste

In [ ]:
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.25, stratify = y, random_state = 42)

In [ ]:
modelo = Perceptron(random_state= 42)
modelo.fit(X_train, y_train)

Perceptron(random_state=42)

In [ ]:
y_pred = modelo.predict(X_test)

In [ ]:
accuracy_score(y_true = y_test, y_pred=y_pred)

1.0

# Exercício - Parte 1

1. Repita o experimento acima, aplicando o Perceptron, porém:
    - Alterando o random_state para o seu número na frequência e escolhendo outro tipo de planta para o teste

# Exercício - Parte 2

1. Aplique o algoritmo do Perceptron aos dados obtidos de diabetes.csv.
    - O seu modelo deve ser chamado de modelo_# onde # é o seu número na frequência da disciplina.
    - Altere o random_state para o seu número na frequência.
    - Qual a acurácia foi encontrada no conjunto de teste?

2. Aplique uma normalização à matriz de atributos X. A nova matriz deve se chamar X_norm

3. Repita o experimento  como uma etapa de pré-processamento.
    - Crie um novo modelo, chamado modeloQ3_# onde # é o seu número na frequência da disciplina.
    - Treine o modelo nos dados normalizados.
    - Indique se o novo modelo possui uma maior acurácia. 